apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 80   # Change to 80 for ALB to work
    targetPort: 4499
    nodePort: 30080   # Optional, or let Kubernetes assign a port
  type: NodePort

