name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO: sanjeev072/wisecow-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .
          docker tag $DOCKERHUB_REPO:$IMAGE_TAG $DOCKERHUB_REPO:latest
          docker push $DOCKERHUB_REPO:$IMAGE_TAG
          docker push $DOCKERHUB_REPO:latest

  deploy-to-eks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'  # Pinned version for stability

      - name: Configure EKS access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config  # Critical security permission
          
          # Verify cluster access
          kubectl config current-context
          kubectl cluster-info
          kubectl get nodes  # This confirms we're using existing cluster

      - name: Deploy to Kubernetes
        run: |
          # Apply configurations
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
          
          # Verify deployment
          kubectl rollout status deployment/wisecow-app
          kubectl get pods -o wide
