name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO: sanjeev072/wisecow-app
  IMAGE_TAG: ${{ github.sha }}
  AWS_REGION: us-east-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .
          docker push $DOCKERHUB_REPO:$IMAGE_TAG

  deploy-to-eks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI and kubectl
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure EKS access
        run: |
          aws eks update-kubeconfig --name wisecow-cluster --region ${{ env.AWS_REGION }}
          kubectl get nodes

      - name: Debug file paths
        run: |
          echo "Listing files in workspace:"
          ls -al

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./deployment.yaml
          kubectl apply -f ./service.yaml
          kubectl apply -f ./ingress.yaml
          
          kubectl rollout status deployment/wisecow-deployment
          kubectl get pods -o wide
          kubectl get svc -o wide
